### ISSUE TITLE
Multiple to states is not possible

### ISSUE THREAD

**Issue by bertdireins** [vadym-kukhtin/angular2-state-machine#1]
The unique StateEvent name restriction makes multiple to states impossible:

```javascript
this.stateMachine = new StateMachine({
            initial: 'firstStep',
            events: [
                new StateEvent({
                     name: 'next', from: ['firstStep'], to: 'secondStep'
                }),
                new StateEvent({
                     name: 'next', from: ['secondStep'], to: 'thirdStep'
                }),
                new StateEvent({
                     name: 'prev', from: ['secondStep'], to: 'firstStep'
                }),
                new StateEvent({
                    name: 'prev', from: ['thirdStep'], to: 'secondStep'
                })                          
            ]
    });
```
Throws `Error: You have to use unique names for all events`

With the original library from jakesgordon this is possible see [here](https://github.com/jakesgordon/javascript-state-machine#multiple-from-and-to-states-for-a-single-event).

**Comment by vadym-k21** [comment]
@bertdireins Hey, This should be fixed, but I will recheck this asap. Sorry for long response, I was busy on main project.

**Comment by vadym-k21** [comment]
because project is going to be deprecated by lacking of time and not so high usage I am going to close this issue
